const express = require("express")
require("dotenv").config()
const cors = require("cors")
const app = express()
const path = require("path")
const fileupload = require("express-fileupload")
app.use(fileupload())
app.use(cors())
app.use(express.json())
app.use("/images",express.static("./controllers/uploads"))
console.log(__dirname)
const connectDB = require("./config/db") 
const router = require("./routes/mainRouter")
connectDB()
app.use(router)
app.listen(process.env.PORT || 3002)