const express = require("express")
const auth = require("../middlewares/auth")
const {create, getAll,deletePost,updatePost, getPost,searchedPost, postComment, getComments, userSpecificPosts, deleteComment} = require("../controllers/postController")
const postRouter = express.Router()
postRouter.post('/create',auth,create)
postRouter.get('/allPosts',getAll)
postRouter.get('/getPost/:id',getPost)
postRouter.post('/comment/:id',auth,postComment)
postRouter.get('/getComments/:id',getComments)
postRouter.get('/profilePosts',auth,userSpecificPosts)
postRouter.delete('/deleteComment/:id/:cmtID',deleteComment)
postRouter.delete('/deletePost/:id',deletePost)
postRouter.put('/updatePost/:id',updatePost)
postRouter.get('/searchPost',searchedPost)
module.exports = postRouter